#!/usr/bin/env bash
# Allows web server to run Nginx as user, to listen on port 8080.

# Update Nginx configuration to run as the nginx user
sed -i 's/user  nginx;/user  nginx nginx;/g' /etc/nginx/nginx.conf

# Modify the default Nginx server block to listen on port 8080
cat > /etc/nginx/conf.d/default.conf <<EOL
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    server_name _;

    location / {
        # Your web server configuration goes here
    }
}
EOL

# Start Nginx
nginx -g 'daemon off;'
